### ISSUE TITLE
Relicense Repository to GPL 

### ISSUE THREAD

**Issue by proudmuslim-dev** [proudmuslim-dev/proudmuslim.tech#5]
This is in order to prevent stealing from this repository and the work that has been put into it.

**Comment by proudmuslim-dev** [comment]
@LunaNotDev @asbyth @MicrocontrollersDev I'll need you guys to give your thoughts on this- I won't relicense unless and until everyone says they're alright with it

**Comment by MicrocontrollersDev** [comment]
👍

**Comment by asbyth** [comment]
sure idc
